spring:
  application:
    name: TaskCan

  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mariadb://localhost:3306/task_cans
    username: root
    password: 3321
  threads:
    virtual:
          enabled: true

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs.html

server:
  port: 3972


logging:
  level:
    root: INFO
